Added the static versions in package.json instead of wildcard *
one-more/react-cron-builder pull request #11
Opened 2019-08-05 07:29 UTC by gr8pathik

I have added the static version in package.json to solve the issue mention in #10. Please accept this PR as soon as possible so people can run this app on local and help to improve this package.

2019-08-27 15:04 UTC, phansys requested changes
Status: Needs work.

2019-08-27 15:04 UTC, phansys commented on .gitignore
> +
Please, remove extra LF at EOF.

2019-08-27 15:04 UTC, phansys commented on .gitignore
> +.DS_Store
Please, don't add environment specific rules to this file. Use [global ignoring rules](https://help.github.com/en/articles/ignoring-files#create-a-global-gitignore) on your environment instead.

2019-08-27 15:04 UTC, phansys commented on package-lock.json
> +{
This is a library, not a project. Why is this file required under the SCM?

2019-08-31 13:56 UTC, one-more commented
fixed in https://github.com/one-more/react-cron-builder/commit/a50928a20cc4b4144858bbdb7a035f2aff244245

2019-08-31 13:56 UTC, closed without merging